apiVersion: v1
kind: Service
metadata:
  name: lh-svc-devops
  labels:
    app: lh-bwce-devops
spec:
  type: LoadBalancer 
  ports:
  - port: 8085
    targetPort: 8080
  selector:
    app: lh-bwce-devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lh-bwce-devops
spec:
  replicas: 1
  selector:
   matchLabels:
    app: lh-bwce-devops
  template:
    metadata:
      name: lh-bwce-devops
      labels:
        app: lh-bwce-devops
    spec:
      containers:
        - name: lh-bwce-devops
          image: santosh1208/bwceapp:helloworld
          imagePullPolicy: Always
          env:

          
          ports:
            - containerPort: 8085
