apiVersion: v1
kind: Service
metadata:
  name: uc3-svc-devops
  labels:
    app: uc3-bwce-devops
spec:
  type: LoadBalancer 
  ports:
  - port: 8088
    targetPort: 8087
  selector:
    app: uc3-bwce-devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc3-bwce-devops
spec:
  replicas: 1
  selector:
   matchLabels:
    app: uc3-bwce-devops
  template:
    metadata:
      name: uc3-bwce-devops
      labels:
        app: uc3-bwce-devops
    spec:
      containers:
        - name: uc3-bwce-devops
          image: santosh1208/sample:mbcp
          imagePullPolicy: Always
          env:

          
          ports:
            - containerPort: 8087
