
apiVersion: v1
kind: Service
metadata:
  name: a1-svc-devops
  labels:
    app: a1-bwce-devops
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: a1-bwce-devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1-bwce-devops
spec:
  replicas: 1
  selector:
   matchLabels:
    app: a1-bwce-devops
  template:
    metadata:
      name: a1-bwce-devops
      labels:
        app: a1-bwce-devops
    spec:
      containers:
        - name: a1-bwce-devops
          image: santosh1208/bwceapp:helloworld
          resources:
            requests:
              memory: "4000Mi"
              cpu: "0.5m"
            limits:
              memory: "4000Mi"
              cpu: "1"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: secret-acr
