{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
spec:
  hosts:  
{{- if .Values.service.name }}
  - {{ .Values.service.name }}
{{- else }}
  - {{ template "fullname" . }}
{{- end }}
  http:    
    route:
    - destination:
{{- if .Values.service.name }}
        name: {{ .Values.service.name }}
{{- else }}
        name: {{ template "fullname" . }}
{{- end }}
        port: {{ .Values.service.externalPort}}              
{{- end }}